-- Haskell module generated by the BNF converter

module SkelInstant where

import qualified AbsInstant

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsInstant.Ident -> Result
transIdent x = case x of
  AbsInstant.Ident string -> failure x
transProgram :: AbsInstant.Program -> Result
transProgram x = case x of
  AbsInstant.Prog stmts -> failure x
transStmt :: AbsInstant.Stmt -> Result
transStmt x = case x of
  AbsInstant.SAss ident exp -> failure x
  AbsInstant.SExp exp -> failure x
transExp :: AbsInstant.Exp -> Result
transExp x = case x of
  AbsInstant.ExpAdd exp1 exp2 -> failure x
  AbsInstant.ExpSub exp1 exp2 -> failure x
  AbsInstant.ExpMul exp1 exp2 -> failure x
  AbsInstant.ExpDiv exp1 exp2 -> failure x
  AbsInstant.ExpLit integer -> failure x
  AbsInstant.ExpVar ident -> failure x

